# Generated by Django 4.2.28 on 2026-03-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
